### ISSUE TITLE
Rechart vertical BarChart not working

### ISSUE THREAD

**Issue by BaaSidDev** [EvHaus/react-pdf-charts#400]
### Describe the bug
i want vertical barchart like this img
<img width="544" alt="image" src="https://github.com/EvHaus/react-pdf-charts/assets/39124286/facfe229-7ea0-408f-a0c8-7fcecf61332e">

but displaying empty chart..
layout="vertical" not working
what should i do??

<img width="543" alt="image" src="https://github.com/EvHaus/react-pdf-charts/assets/39124286/43293bf6-840c-4dc7-9255-aef8f01c78fc">
<img width="727" alt="image" src="https://github.com/EvHaus/react-pdf-charts/assets/39124286/6d4894b1-06f5-4a6c-9ff7-846983061a2c">

### Reproduction

https://stackblitz.com/edit/react-pdf-charts-starter-5byukq?file=src%2FApp.tsx

### Validations

- [X] Check that there isn't [already an issue](https://github.com/EvHaus/react-pdf-charts/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that you're confident that this is a legitimate bug. To ask a question open a [GitHub Discussion](https://github.com/EvHaus/react-pdf-charts/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by EvHaus** [comment]
@BaaSidDev Looks like this is is not a bug with `react-pdf-charts` but rather with your `recharts` code. Your chart configuration in the web version of `recharts` also doesn't render anything: https://stackblitz.com/edit/recharts-example-4nwyda?file=index.js

I think the issue is that your `XAxis` and `YAxis` values aren't specifying which data to use. If you change those to:

```ts
<XAxis dataKey="amt" type="number" />
<YAxis dataKey="name" type="category" />
```

then you'll get the result I think you want:

![image](https://github.com/EvHaus/react-pdf-charts/assets/226640/cc18238c-fce6-4217-8163-6b8d2079a4da)

And it also works in `react-pdf-charts`:

![image](https://github.com/EvHaus/react-pdf-charts/assets/226640/8fdbea3c-5f7e-49a1-a963-d2eceee462de)

**Comment by jaemushim** [comment]
this is my mistake..  
Thank you very much.
