### ISSUE TITLE
Font size and color support

### ISSUE THREAD

**Issue by mortocks** [EvHaus/react-pdf-charts#46]
Any chance the library will be able to support ```fontSize``` and ```color``` properties for Text elements (Mainly used in chart axis elements? 

This will obviously be a challenge as different libraries use different attributes to style them so a generic interface will be difficult.

e.g.

```tsx
// Recharts
<XAxis tick={{fontSize: 5}} />

// Victory Charts
<VictoryAxis
  style={
    tickLabels: { fontSize: 2 }, // style for the axis label
    axisLabel: { fontSize: 10 }, // style for the "tick" labels
  }
/>
```

The libraries I'm familiar with tend to support most ```React.CSSProperties``` although some nest these to support sub elements (i.e. VictoryCharts). ```fontFamily``` would also be useful.

**Comment by EvHaus** [comment]
Just published v0.2.0 with some basic support for this. Note that in most cases `color` is the wrong style attribute for labels, you'll need to use `fill` instead.

I also decided not to add support for `font-family` in Victory because Victory by default uses `'Gill Sans', 'Seravek', 'Trebuchet MS', sans-serif` and `react-pdf` complains with:

```
error: Font family not registered: 'Gill Sans', 'Seravek', 'Trebuchet MS', sans-serif. Please register it calling Font.register() method.
```

I think that makes this hard to use as you'll need to define a Victory theme that uses a simpler font family. You can specify a `font-family` for the whole chart by passing in a `fontFamily` style to the outer `<ReactPDFChart />` container element instead.
